import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const offers = [
  {
    name: 'Займер',
    slug: 'zaymer',
    rating: 4.8,
    minAmount: 1000,
    maxAmount: 30000,
    minTerm: 7,
    maxTerm: 30,
    baseRate: 0.63,
    firstLoanRate: 0,
    decisionTime: 2,
    approvalRate: 94,
    payoutMethods: ['card', 'yoomoney', 'qiwi', 'contact'],
    features: ['first_loan_zero', 'online_approval', 'one_document', 'prolongation'],
    badCreditOk: true,
    noCalls: true,
    roundTheClock: true,
    minAge: 18,
    documents: ['passport'],
    customDescription: 'Надёжный сервис с высоким процентом одобрения. Подходит для первого займа.',
    affiliateUrl: '#',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    status: 'published',
    showOnHomepage: true,
    sortOrder: 1,
  },
  {
    name: 'MoneyMan',
    slug: 'moneyman',
    rating: 4.6,
    minAmount: 1500,
    maxAmount: 80000,
    minTerm: 5,
    maxTerm: 126,
    baseRate: 0.5,
    firstLoanRate: 0,
    decisionTime: 1,
    approvalRate: 91,
    payoutMethods: ['card', 'bank_account', 'contact'],
    features: ['first_loan_zero', 'prolongation', 'early_repayment', 'loyalty_program'],
    badCreditOk: true,
    noCalls: true,
    roundTheClock: false,
    minAge: 18,
    documents: ['passport'],
    customDescription: 'Крупные суммы до 80 000 ₽. Удобно для тех, кому нужно больше денег.',
    affiliateUrl: '#',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    status: 'published',
    showOnHomepage: true,
    sortOrder: 2,
  },
  {
    name: 'еКапуста',
    slug: 'ekapusta',
    rating: 4.7,
    minAmount: 100,
    maxAmount: 30000,
    minTerm: 7,
    maxTerm: 21,
    baseRate: 0.0,
    firstLoanRate: 0,
    decisionTime: 0,
    approvalRate: 97,
    payoutMethods: ['card', 'yoomoney', 'qiwi', 'contact', 'golden_crown'],
    features: ['first_loan_zero', 'no_overpayments', 'online_approval', 'one_document'],
    badCreditOk: true,
    noCalls: true,
    roundTheClock: true,
    minAge: 18,
    documents: ['passport'],
    customDescription: 'Моментальное решение и выдача. Минимальная сумма от 100 ₽.',
    affiliateUrl: '#',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    status: 'published',
    showOnHomepage: true,
    sortOrder: 3,
  },
  {
    name: 'Турбозайм',
    slug: 'turbozaim',
    rating: 4.5,
    minAmount: 1000,
    maxAmount: 50000,
    minTerm: 7,
    maxTerm: 182,
    baseRate: 0.77,
    firstLoanRate: 0,
    decisionTime: 5,
    approvalRate: 89,
    payoutMethods: ['card', 'contact', 'golden_crown'],
    features: ['first_loan_zero', 'prolongation', 'early_repayment'],
    badCreditOk: true,
    noCalls: false,
    roundTheClock: false,
    minAge: 21,
    documents: ['passport'],
    customDescription: 'Длинные сроки до 6 месяцев. Возможность пролонгации.',
    affiliateUrl: '#',
    isFeatured: false,
    isNew: false,
    isPopular: true,
    status: 'published',
    showOnHomepage: true,
    sortOrder: 4,
  },
  {
    name: 'Moneza',
    slug: 'moneza',
    rating: 4.4,
    minAmount: 2000,
    maxAmount: 30000,
    minTerm: 5,
    maxTerm: 35,
    baseRate: 0.5,
    firstLoanRate: 0,
    decisionTime: 3,
    approvalRate: 86,
    payoutMethods: ['card', 'contact'],
    features: ['first_loan_zero', 'online_approval', 'one_document'],
    badCreditOk: true,
    noCalls: true,
    roundTheClock: false,
    minAge: 18,
    documents: ['passport'],
    customDescription: 'Простой сервис с быстрым решением. Хороший выбор для новичков.',
    affiliateUrl: '#',
    isFeatured: false,
    isNew: true,
    isPopular: false,
    status: 'published',
    showOnHomepage: true,
    sortOrder: 5,
  },
  {
    name: 'Webbankir',
    slug: 'webbankir',
    rating: 4.5,
    minAmount: 1000,
    maxAmount: 50000,
    minTerm: 1,
    maxTerm: 365,
    baseRate: 0.45,
    firstLoanRate: 0,
    decisionTime: 10,
    approvalRate: 88,
    payoutMethods: ['card', 'bank_account', 'yoomoney'],
    features: ['first_loan_zero', 'prolongation', 'early_repayment', 'loyalty_program'],
    badCreditOk: true,
    noCalls: true,
    roundTheClock: true,
    minAge: 18,
    documents: ['passport', 'inn'],
    customDescription: 'Гибкие сроки от 1 дня до года. Программа лояльности для постоянных клиентов.',
    affiliateUrl: '#',
    isFeatured: false,
    isNew: false,
    isPopular: false,
    status: 'published',
    showOnHomepage: true,
    sortOrder: 6,
  },
  {
    name: 'До зарплаты',
    slug: 'do-zarplaty',
    rating: 4.3,
    minAmount: 2000,
    maxAmount: 100000,
    minTerm: 7,
    maxTerm: 180,
    baseRate: 0.5,
    firstLoanRate: 0.3,
    decisionTime: 15,
    approvalRate: 82,
    payoutMethods: ['card', 'bank_account'],
    features: ['prolongation', 'early_repayment'],
    badCreditOk: true,
    noCalls: false,
    roundTheClock: false,
    minAge: 21,
    documents: ['passport', 'inn'],
    customDescription: 'Крупные суммы до 100 000 ₽. Подходит для тех, кому нужно больше денег.',
    affiliateUrl: '#',
    isFeatured: false,
    isNew: false,
    isPopular: false,
    status: 'published',
    showOnHomepage: true,
    sortOrder: 7,
  },
  {
    name: 'Lime',
    slug: 'lime',
    rating: 4.6,
    minAmount: 1000,
    maxAmount: 70000,
    minTerm: 10,
    maxTerm: 90,
    baseRate: 0.55,
    firstLoanRate: 0,
    decisionTime: 1,
    approvalRate: 92,
    payoutMethods: ['card', 'contact', 'golden_crown'],
    features: ['first_loan_zero', 'online_approval', 'prolongation', 'early_repayment'],
    badCreditOk: true,
    noCalls: true,
    roundTheClock: true,
    minAge: 18,
    documents: ['passport'],
    customDescription: 'Высокий процент одобрения. Работает круглосуточно.',
    affiliateUrl: '#',
    isFeatured: true,
    isNew: false,
    isPopular: true,
    status: 'published',
    showOnHomepage: true,
    sortOrder: 8,
  },
];

async function main() {
  console.log('Start seeding...');

  // Clear existing offers
  await prisma.loanOffer.deleteMany({});
  console.log('Cleared existing offers');

  // Create offers
  for (const offer of offers) {
    const created = await prisma.loanOffer.create({
      data: {
        name: offer.name,
        slug: offer.slug,
        rating: offer.rating,
        minAmount: offer.minAmount,
        maxAmount: offer.maxAmount,
        minTerm: offer.minTerm,
        maxTerm: offer.maxTerm,
        baseRate: offer.baseRate,
        firstLoanRate: offer.firstLoanRate,
        decisionTime: offer.decisionTime,
        approvalRate: offer.approvalRate,
        payoutMethods: JSON.stringify(offer.payoutMethods),
        features: JSON.stringify(offer.features),
        badCreditOk: offer.badCreditOk,
        noCalls: offer.noCalls,
        roundTheClock: offer.roundTheClock,
        minAge: offer.minAge,
        documents: JSON.stringify(offer.documents),
        customDescription: offer.customDescription,
        affiliateUrl: offer.affiliateUrl,
        isFeatured: offer.isFeatured,
        isNew: offer.isNew,
        isPopular: offer.isPopular,
        status: offer.status,
        showOnHomepage: offer.showOnHomepage,
        sortOrder: offer.sortOrder,
        syncStatus: 'synced',
      },
    });
    console.log(`Created offer: ${created.name}`);
  }

  console.log('Seeding finished!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
